### ISSUE TITLE
哥们儿! 请教你一个关于音乐播放锁屏后. 拖动进度条播放卡顿如何解决

### ISSUE THREAD

**Issue by DevLiuSir** [johnlui/Swift-MMP#2]
哥们儿! 请教你一个关于音乐播放锁屏后. 拖动进度条播放卡顿如何解决

**Comment by johnlui** [comment]
没遇到过呀。。。播放的是本地的音乐吗？网络音乐用缓存了吗？如果是本地音乐那八成就是设备性能不足了。。。Xcode 9 的模拟器性能很差，在黑苹果上尤甚。
